{% set version = "0.2.5" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 9c38283ce4664ec105e78f068abb0e51d9ed165a2ddf3191b0d14a4888375ee6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6,<3.7
    - pip
    - pytest-runner
  run:
    - python >=3.6,<3.7
    - setuptools
    - dataclasses
    - nbconvert

test:
  imports:
    - importnb

about:
  home: https://github.com/deathbeds/importnb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Import .ipynb files as modules in the system path

extra:
  recipe-maintainers:
    - ocefpaf
