{% set version = "0.7.0" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 067289b46ea412def63b4bb9b28e15f659badf4176defe5bd75ffd8078040a0e

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - importnb-install = importnb.utils.ipython:install
    - importnb-uninstall = importnb.utils.ipython:uninstall
    - nbdoctest = importnb.utils.nbdoctest:_test

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - dataclasses  # [py<37]
    - importlib_resources  # [py<37]

test:
  requires:
    - ipython
  imports:
    - importnb
  commands:
    - importnb-install --help
    - importnb-uninstall --help
    - nbdoctest --help

about:
  home: https://github.com/deathbeds/importnb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Import Jupyter (ne IPython) notebooks into tests and scripts.
  doc_url: https://importnb.readthedocs.io
  doc_source_url: https://github.com/deathbeds/importnb/tree/{{ version }}/docs
  description: |
    importnb imports notebooks as modules. Notebooks are reusable as tests,
    source code, importable modules, and command line utilities.

extra:
  recipe-maintainers:
    - ocefpaf
    - bollwyvl
