{% set version = "0.5.2" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 649659ca7bc4151ca272bfa7cf6753501afbc5db28bf5bc0cc1e4039aea3892c

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
    - wheel >=0.31.0
    - twine >=1.11.0
  run:
    - python >=3
    - setuptools
    - dataclasses
    - nbconvert
    # importlib_resources will be [not py>36] and this will be arch again :-(
    - importlib_resources

test:
  imports:
    - importnb

about:
  home: https://github.com/deathbeds/importnb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Import .ipynb files as modules in the system path

extra:
  recipe-maintainers:
    - ocefpaf
