travis:
  secure:
    BINSTAR_TOKEN: pCw75tLeYePEyYw7mxQomshRc3fuY1NpEQG4AdaABtsCSga7pEViKC3lzTi2qEXj03OFNql8hGszbgAdMkJ4+35nvTrY/JKvUjIydg9E6oBmQIfIne4DAmeHTqqvtkQi6PyfFvyIdC4c9nIFhbmGwTTIQT024nQ1LctjB/0w30imqk7r0hnn0tWiOMSZ2p/Fg61tcTxMBDvjhK/y/5WvJB3bTzWZIA0c0OyeP6BGTJ/MT3tCMBjWb24oCNsGL5z/Omqb0ZCewWL+2k3UzO0If+rYUoEjmt/95X88LqENacWH7tRVxB4ypuDEnaxaMFUcKno4Xu/OQfq2szf75Ma6YAJDJoDTvvZ7BoSa8h+6BwdRSuhWUW9g80LzdvNe1htyHOs0kvJrzku03D6ByeZA/VhoRLaBaw8JwKpctaZvXK3Y/lv1/srv6cbIQ7xPClXhQkhZ3vdwvDL37XOqNThQCu047IGiA2kA29cKRYgitybq8W5U5rycAe9DOkP1GetwmevbroFaLo1Vq2xnllIQtb1F6Qjy6H4ypadCpoyBEeI+IpWrQAMLYi2ZzfQ6pLMj6h+HRCkEvpfI3T7znvIM4dylgTZFbn43TlyzbiJo6/L5HoV5cCj+A/QSoVTAu9dEY6Ipk1xaspZpbVu6Xx/fMPfRFRlnWVXwnLyjtTGD49Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
