travis:
  secure:
    BINSTAR_TOKEN: xHRtMCk6DKBS23+rFDuVAGvRVayS3nthWZ7lKvGkIx1W83r2PNJIrJ58iJ0fbpvnOY9Xda5SnCJZWL7md60kRrdzudnFc/8EPBIrt0Yi4dNVTE1qvILWn756hfjXMREBvq1RRwv7XAa/Evamzq5s13C8raGtP/qVByg8IOplwfVvfdvY79KusIeooismdipgIyjZCL5HWrfgnEnBVF7Y9fe0wqsgbbni/TzW66evV6RDg00t56l8ZDUytEKa9A95Mqh4aFJLeGfFO15qjTuZ5zUPT64N/bQq/orzjkuRpVIj0Fu+oVXxX9LbsJvV5EZXgyPGD54PWsBvw6/vsJ37msSGQ0nKBiZ9RIWYqpk4T2PclOEwx7XRlqAvvkRxahvM0LzWNzhx4uIJHVZTgU2KBBSmLw+0+Q1wNf/3QpXa/f1LWYHotIL61E6GBPl5vd+k2Pfk1/0SVTG5Lgv3dM/ZXCzHU3w7EaH33zllUmWsaRhJfu2AVYmvS4PWdRul63o8yya/Sk/ja0uwvffehnFpP4bsTZ0CbRAMtaqXLAsR7OvaKugVP0uso8o9PqmizEj8XOrGzJO+SjU7SGTZmFu7jWIuPFx+We8Y+YvMe6zJxsRFyFrAO7FrS+qK+GEg0T7nH1M1I0jFJR4lioyH5TRf0LyyCZFrHnzZQuc8Bh8mwZg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
